

def break_clusters(clusters, perc=0.2, c_size=2):

    n_clusters = len(clusters.keys())
    sel_cluster = int(n_clusters * (1-perc))
    new_clusters = {}

    for key,values in clusters.items():

        if (key<sel_cluster):
            new_clusters[key] = clusters[key]
            continue

        if len(values)<=c_size:
            new_clusters[key] = clusters[key]
            continue

        for i,cc in enumerate(clusters[key]):
            new_clusters['c_'+str(key)+'_'+str(i)] = [cc]

        
    return new_clusters


dom_clusters = {
    'onc_easy': {

    'charisma': {
  0: ['feature_charisma8', 'feature_charisma15'],
  1: ['feature_charisma10', 'feature_charisma78'],
  2: ['feature_charisma44', 'feature_charisma74'],
  3: ['feature_charisma9', 'feature_charisma69'],
  4: ['feature_charisma20', 'feature_charisma64'],
  5: ['feature_charisma23', 'feature_charisma39'],
  6: ['feature_charisma31', 'feature_charisma51'],
  7: ['feature_charisma43', 'feature_charisma70'],
  8: ['feature_charisma32', 'feature_charisma48'],
  9: ['feature_charisma16', 'feature_charisma35'],
  10: ['feature_charisma57', 'feature_charisma83'],
  11: ['feature_charisma13', 'feature_charisma50'],
  12: ['feature_charisma49', 'feature_charisma73'],
  13: ['feature_charisma26', 'feature_charisma67'],
  14: ['feature_charisma46', 'feature_charisma66'],
  15: ['feature_charisma42', 'feature_charisma75'],
  16: ['feature_charisma3', 'feature_charisma45'],
  17: ['feature_charisma63', 'feature_charisma85'],
  18: ['feature_charisma27', 'feature_charisma77'],
  19: ['feature_charisma12', 'feature_charisma80'],
  20: ['feature_charisma68', 'feature_charisma82'],
  21: ['feature_charisma25', 'feature_charisma47'],
  22: ['feature_charisma84', 'feature_charisma86'],
  23: ['feature_charisma30', 'feature_charisma38'],
  24: ['feature_charisma40', 'feature_charisma61'],
  25: ['feature_charisma52', 'feature_charisma62'],
  26: ['feature_charisma2', 'feature_charisma24'],
  27: ['feature_charisma1', 'feature_charisma19'],
  28: ['feature_charisma4', 'feature_charisma17'],
  29: ['feature_charisma21', 'feature_charisma36'],
  30: ['feature_charisma29', 'feature_charisma71'],
  31: ['feature_charisma5', 'feature_charisma79'],
  32: ['feature_charisma34', 'feature_charisma55'],
  33: ['feature_charisma14', 'feature_charisma33'],
  34: ['feature_charisma56', 'feature_charisma65'],
  35: ['feature_charisma28', 'feature_charisma53'],
  36: ['feature_charisma41', 'feature_charisma59'],
  37: ['feature_charisma6', 'feature_charisma54'],
  38: ['feature_charisma22', 'feature_charisma60'],
  39: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  40: ['feature_charisma7', 'feature_charisma72'],
  41: ['feature_charisma11', 'feature_charisma58']},
 'constitution': {0: ['feature_constitution86', 'feature_constitution94'],
  1: ['feature_constitution21', 'feature_constitution70'],
  2: ['feature_constitution52', 'feature_constitution69'],
  3: ['feature_constitution24', 'feature_constitution82'],
  4: ['feature_constitution59', 'feature_constitution81'],
  5: ['feature_constitution46', 'feature_constitution112'],
  6: ['feature_constitution76', 'feature_constitution89'],
  7: ['feature_constitution34', 'feature_constitution36'],
  8: ['feature_constitution53', 'feature_constitution71'],
  9: ['feature_constitution16', 'feature_constitution40'],
  10: ['feature_constitution30', 'feature_constitution42'],
  11: ['feature_constitution3', 'feature_constitution23'],
  12: ['feature_constitution45', 'feature_constitution47'],
  13: ['feature_constitution41', 'feature_constitution108'],
  14: ['feature_constitution15', 'feature_constitution37'],
  15: ['feature_constitution83', 'feature_constitution100'],
  16: ['feature_constitution58', 'feature_constitution68'],
  17: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  18: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  19: ['feature_constitution72',
   'feature_constitution88',
   'feature_constitution90',
   'feature_constitution103'],
  20: ['feature_constitution8', 'feature_constitution17'],
  21: ['feature_constitution54', 'feature_constitution95'],
  22: ['feature_constitution11', 'feature_constitution28'],
  23: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  24: ['feature_constitution18',
   'feature_constitution39',
   'feature_constitution97',
   'feature_constitution107'],
  25: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution74'],
  26: ['feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution77'],
  27: ['feature_constitution19', 'feature_constitution78'],
  28: ['feature_constitution61', 'feature_constitution96'],
  29: ['feature_constitution31', 'feature_constitution104'],
  30: ['feature_constitution63', 'feature_constitution65'],
  31: ['feature_constitution9',
   'feature_constitution33',
   'feature_constitution60',
   'feature_constitution87'],
  32: ['feature_constitution14', 'feature_constitution51'],
  33: ['feature_constitution2', 'feature_constitution73'],
  34: ['feature_constitution12',
   'feature_constitution29',
   'feature_constitution50',
   'feature_constitution101'],
  35: ['feature_constitution22',
   'feature_constitution25',
   'feature_constitution75',
   'feature_constitution106'],
  36: ['feature_constitution38',
   'feature_constitution67',
   'feature_constitution111',
   'feature_constitution114'],
  37: ['feature_constitution1',
   'feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution62',
   'feature_constitution80',
   'feature_constitution84',
   'feature_constitution85'],
  38: ['feature_constitution35',
   'feature_constitution105',
   'feature_constitution109',
   'feature_constitution113',
   'feature_constitution4',
   'feature_constitution49'],
  39: ['feature_constitution64',
   'feature_constitution92',
   'feature_constitution98',
   'feature_constitution99']},
 'dexterity': {0: ['feature_dexterity4', 'feature_dexterity7'],
  1: ['feature_dexterity12', 'feature_dexterity14'],
  2: ['feature_dexterity3', 'feature_dexterity8'],
  3: ['feature_dexterity6', 'feature_dexterity11'],
  4: ['feature_dexterity2',
   'feature_dexterity10',
   'feature_dexterity5',
   'feature_dexterity13'],
  5: ['feature_dexterity1', 'feature_dexterity9']},
 'intelligence': {0: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence5',
   'feature_intelligence6',
   'feature_intelligence7',
   'feature_intelligence12'],
  1: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence9',
   'feature_intelligence10',
   'feature_intelligence11']},
 'strength': {0: ['feature_strength20', 'feature_strength38'],
  1: ['feature_strength18', 'feature_strength37'],
  2: ['feature_strength5', 'feature_strength13'],
  3: ['feature_strength3', 'feature_strength19'],
  4: ['feature_strength14', 'feature_strength34'],
  5: ['feature_strength10', 'feature_strength36'],
  6: ['feature_strength9', 'feature_strength22'],
  7: ['feature_strength16', 'feature_strength23'],
  8: ['feature_strength15', 'feature_strength27'],
  9: ['feature_strength2', 'feature_strength32'],
  10: ['feature_strength6', 'feature_strength17'],
  11: ['feature_strength12', 'feature_strength30'],
  12: ['feature_strength26', 'feature_strength33'],
  13: ['feature_strength24', 'feature_strength29'],
  14: ['feature_strength11', 'feature_strength21'],
  15: ['feature_strength1', 'feature_strength4'],
  16: ['feature_strength8', 'feature_strength28'],
  17: ['feature_strength25', 'feature_strength31'],
  18: ['feature_strength7', 'feature_strength35']},
 'wisdom': {0: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45'],
  1: ['feature_wisdom6', 'feature_wisdom11'],
  2: ['feature_wisdom10', 'feature_wisdom19'],
  3: ['feature_wisdom9', 'feature_wisdom22'],
  4: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  5: ['feature_wisdom8', 'feature_wisdom26'],
  6: ['feature_wisdom17', 'feature_wisdom29'],
  7: ['feature_wisdom18', 'feature_wisdom25'],
  8: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44'],
  9: ['feature_wisdom15',
   'feature_wisdom21',
   'feature_wisdom27',
   'feature_wisdom28'],
  10: ['feature_wisdom36', 'feature_wisdom42'],
  11: ['feature_wisdom1',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35',
   'feature_wisdom13',
   'feature_wisdom23',
   'feature_wisdom32'],
  12: ['feature_wisdom31',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom3',
   'feature_wisdom43',
   'feature_wisdom24',
   'feature_wisdom33']}
   },
    
 'onc_hard': {
 'charisma': {
  0: ['feature_charisma8', 'feature_charisma15'],
  1: ['feature_charisma1', 'feature_charisma19'],
  2: ['feature_charisma26', 'feature_charisma67'],
  3: ['feature_charisma27', 'feature_charisma77'],
  4: ['feature_charisma57', 'feature_charisma83'],
  5: ['feature_charisma32', 'feature_charisma48'],
  6: ['feature_charisma23', 'feature_charisma39'],
  7: ['feature_charisma25', 'feature_charisma47'],
  8: ['feature_charisma11', 'feature_charisma58'],
  9: ['feature_charisma9', 'feature_charisma69'],
  10: ['feature_charisma46', 'feature_charisma66'],
  11: ['feature_charisma16', 'feature_charisma35'],
  12: ['feature_charisma2', 'feature_charisma24'],
  13: ['feature_charisma56', 'feature_charisma65'],
  14: ['feature_charisma68', 'feature_charisma82'],
  15: ['feature_charisma3', 'feature_charisma45'],
  16: ['feature_charisma22', 'feature_charisma60'],
  17: ['feature_charisma84', 'feature_charisma86'],
  18: ['feature_charisma44', 'feature_charisma74'],
  19: ['feature_charisma20', 'feature_charisma64'],
  20: ['feature_charisma13', 'feature_charisma50'],
  21: ['feature_charisma31', 'feature_charisma51'],
  22: ['feature_charisma34', 'feature_charisma55'],
  23: ['feature_charisma52', 'feature_charisma62'],
  24: ['feature_charisma49', 'feature_charisma73'],
  25: ['feature_charisma41', 'feature_charisma59'],
  26: ['feature_charisma14', 'feature_charisma33'],
  27: ['feature_charisma43',
   'feature_charisma63',
   'feature_charisma70',
   'feature_charisma85'],
  28: ['feature_charisma12', 'feature_charisma80'],
  29: ['feature_charisma6', 'feature_charisma54'],
  30: ['feature_charisma10', 'feature_charisma78'],
  31: ['feature_charisma21', 'feature_charisma36'],
  32: ['feature_charisma5', 'feature_charisma79'],
  33: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  34: ['feature_charisma42', 'feature_charisma75'],
  35: ['feature_charisma7', 'feature_charisma72'],
  36: ['feature_charisma28', 'feature_charisma53'],
  37: ['feature_charisma4',
   'feature_charisma17',
   'feature_charisma30',
   'feature_charisma38'],
  38: ['feature_charisma40',
   'feature_charisma61',
   'feature_charisma29',
   'feature_charisma71']},
 'constitution': {0: ['feature_constitution11', 'feature_constitution28'],
  1: ['feature_constitution19', 'feature_constitution78'],
  2: ['feature_constitution34', 'feature_constitution36'],
  3: ['feature_constitution16', 'feature_constitution40'],
  4: ['feature_constitution72', 'feature_constitution103'],
  5: ['feature_constitution52', 'feature_constitution69'],
  6: ['feature_constitution30', 'feature_constitution42'],
  7: ['feature_constitution21', 'feature_constitution70'],
  8: ['feature_constitution41', 'feature_constitution108'],
  9: ['feature_constitution8', 'feature_constitution17'],
  10: ['feature_constitution88', 'feature_constitution90'],
  11: ['feature_constitution3', 'feature_constitution23'],
  12: ['feature_constitution59', 'feature_constitution81'],
  13: ['feature_constitution53', 'feature_constitution71'],
  14: ['feature_constitution76', 'feature_constitution89'],
  15: ['feature_constitution24', 'feature_constitution82'],
  16: ['feature_constitution46', 'feature_constitution112'],
  17: ['feature_constitution31', 'feature_constitution104'],
  18: ['feature_constitution86', 'feature_constitution94'],
  19: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  20: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  21: ['feature_constitution83',
   'feature_constitution100',
   'feature_constitution58',
   'feature_constitution68'],
  22: ['feature_constitution64',
   'feature_constitution92',
   'feature_constitution98',
   'feature_constitution99'],
  23: ['feature_constitution15', 'feature_constitution37'],
  24: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  25: ['feature_constitution38',
   'feature_constitution67',
   'feature_constitution111',
   'feature_constitution114'],
  26: ['feature_constitution12', 'feature_constitution101'],
  27: ['feature_constitution29', 'feature_constitution50'],
  28: ['feature_constitution9',
   'feature_constitution14',
   'feature_constitution33',
   'feature_constitution45',
   'feature_constitution47',
   'feature_constitution51',
   'feature_constitution54',
   'feature_constitution60',
   'feature_constitution61',
   'feature_constitution87',
   'feature_constitution95',
   'feature_constitution96'],
  29: ['feature_constitution22',
   'feature_constitution25',
   'feature_constitution75',
   'feature_constitution106',
   'feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution74',
   'feature_constitution77',
   'feature_constitution18',
   'feature_constitution39',
   'feature_constitution97',
   'feature_constitution107'],
  30: ['feature_constitution1',
   'feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution62',
   'feature_constitution80',
   'feature_constitution84',
   'feature_constitution85'],
  31: ['feature_constitution2',
   'feature_constitution73',
   'feature_constitution63',
   'feature_constitution65'],
  32: ['feature_constitution4',
   'feature_constitution35',
   'feature_constitution49',
   'feature_constitution105',
   'feature_constitution109',
   'feature_constitution113']},
 'dexterity': {0: ['feature_dexterity5', 'feature_dexterity13'],
  1: ['feature_dexterity4', 'feature_dexterity7'],
  2: ['feature_dexterity2', 'feature_dexterity10'],
  3: ['feature_dexterity12', 'feature_dexterity14'],
  4: ['feature_dexterity3',
   'feature_dexterity8',
   'feature_dexterity6',
   'feature_dexterity11'],
  5: ['feature_dexterity1', 'feature_dexterity9']},
 'intelligence': {0: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence5',
   'feature_intelligence6',
   'feature_intelligence7',
   'feature_intelligence12'],
  1: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence9',
   'feature_intelligence10',
   'feature_intelligence11']},
 'strength': {0: ['feature_strength2', 'feature_strength32'],
  1: ['feature_strength10', 'feature_strength36'],
  2: ['feature_strength6', 'feature_strength17'],
  3: ['feature_strength5', 'feature_strength13'],
  4: ['feature_strength7', 'feature_strength35'],
  5: ['feature_strength9', 'feature_strength22'],
  6: ['feature_strength20', 'feature_strength38'],
  7: ['feature_strength24', 'feature_strength29'],
  8: ['feature_strength3', 'feature_strength19'],
  9: ['feature_strength14', 'feature_strength34'],
  10: ['feature_strength8', 'feature_strength28'],
  11: ['feature_strength16', 'feature_strength23'],
  12: ['feature_strength25', 'feature_strength31'],
  13: ['feature_strength26', 'feature_strength33'],
  14: ['feature_strength12', 'feature_strength30'],
  15: ['feature_strength18', 'feature_strength37'],
  16: ['feature_strength1',
   'feature_strength4',
   'feature_strength11',
   'feature_strength21'],
  17: ['feature_strength15', 'feature_strength27']},
 'wisdom': {0: ['feature_wisdom23', 'feature_wisdom32'],
  1: ['feature_wisdom15', 'feature_wisdom27'],
  2: ['feature_wisdom9', 'feature_wisdom22'],
  3: ['feature_wisdom18', 'feature_wisdom25'],
  4: ['feature_wisdom8', 'feature_wisdom26'],
  5: ['feature_wisdom6', 'feature_wisdom11'],
  6: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44'],
  7: ['feature_wisdom10', 'feature_wisdom19'],
  8: ['feature_wisdom17', 'feature_wisdom29'],
  9: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  10: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  11: ['feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43',
   'feature_wisdom21',
   'feature_wisdom28'],
  12: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35'],
  13: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45']}
   },


'information_variation_easy': {

'charisma': {
  0: ['feature_charisma31', 'feature_charisma51'],
  1: ['feature_charisma57', 'feature_charisma83'],
  2: ['feature_charisma30', 'feature_charisma38'],
  3: ['feature_charisma27', 'feature_charisma77'],
  4: ['feature_charisma42', 'feature_charisma75'],
  5: ['feature_charisma40', 'feature_charisma61'],
  6: ['feature_charisma23', 'feature_charisma39'],
  7: ['feature_charisma10', 'feature_charisma78'],
  8: ['feature_charisma26', 'feature_charisma67'],
  9: ['feature_charisma8', 'feature_charisma15'],
  10: ['feature_charisma6', 'feature_charisma54'],
  11: ['feature_charisma20', 'feature_charisma64'],
  12: ['feature_charisma13', 'feature_charisma50'],
  13: ['feature_charisma46', 'feature_charisma66'],
  14: ['feature_charisma29', 'feature_charisma71'],
  15: ['feature_charisma68', 'feature_charisma82'],
  16: ['feature_charisma56', 'feature_charisma65'],
  17: ['feature_charisma32', 'feature_charisma48'],
  18: ['feature_charisma44', 'feature_charisma74'],
  19: ['feature_charisma84', 'feature_charisma86'],
  20: ['feature_charisma3', 'feature_charisma45'],
  21: ['feature_charisma34', 'feature_charisma55'],
  22: ['feature_charisma16', 'feature_charisma35'],
  23: ['feature_charisma43', 'feature_charisma70'],
  24: ['feature_charisma49', 'feature_charisma73'],
  25: ['feature_charisma2', 'feature_charisma24'],
  26: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  27: ['feature_charisma22', 'feature_charisma60'],
  28: ['feature_charisma63', 'feature_charisma85'],
  29: ['feature_charisma4', 'feature_charisma17'],
  30: ['feature_charisma25',
   'feature_charisma47',
   'feature_charisma7',
   'feature_charisma72'],
  31: ['feature_charisma14',
   'feature_charisma33',
   'feature_charisma52',
   'feature_charisma62',
   'feature_charisma12',
   'feature_charisma80'],
  32: ['feature_charisma1',
   'feature_charisma19',
   'feature_charisma9',
   'feature_charisma69'],
  33: ['feature_charisma21',
   'feature_charisma36',
   'feature_charisma28',
   'feature_charisma53',
   'feature_charisma11',
   'feature_charisma58'],
  34: ['feature_charisma5',
   'feature_charisma79',
   'feature_charisma41',
   'feature_charisma59']},
 'constitution': {0: ['feature_constitution24', 'feature_constitution82'],
  1: ['feature_constitution86', 'feature_constitution94'],
  2: ['feature_constitution61', 'feature_constitution96'],
  3: ['feature_constitution15', 'feature_constitution37'],
  4: ['feature_constitution16', 'feature_constitution40'],
  5: ['feature_constitution46', 'feature_constitution112'],
  6: ['feature_constitution58', 'feature_constitution68'],
  7: ['feature_constitution52', 'feature_constitution69'],
  8: ['feature_constitution41', 'feature_constitution108'],
  9: ['feature_constitution53', 'feature_constitution71'],
  10: ['feature_constitution31', 'feature_constitution104'],
  11: ['feature_constitution3', 'feature_constitution23'],
  12: ['feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution77'],
  13: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  14: ['feature_constitution34', 'feature_constitution36'],
  15: ['feature_constitution8', 'feature_constitution17'],
  16: ['feature_constitution21', 'feature_constitution70'],
  17: ['feature_constitution72',
   'feature_constitution88',
   'feature_constitution90',
   'feature_constitution103'],
  18: ['feature_constitution19', 'feature_constitution78'],
  19: ['feature_constitution11', 'feature_constitution28'],
  20: ['feature_constitution14', 'feature_constitution51'],
  21: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution74'],
  22: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  23: ['feature_constitution18',
   'feature_constitution39',
   'feature_constitution97',
   'feature_constitution107'],
  24: ['feature_constitution38',
   'feature_constitution67',
   'feature_constitution111',
   'feature_constitution114'],
  25: ['feature_constitution2', 'feature_constitution73'],
  26: ['feature_constitution63', 'feature_constitution65'],
  27: ['feature_constitution30',
   'feature_constitution42',
   'feature_constitution59',
   'feature_constitution81'],
  28: ['feature_constitution12',
   'feature_constitution101',
   'feature_constitution29',
   'feature_constitution50'],
  29: ['feature_constitution22',
   'feature_constitution25',
   'feature_constitution75',
   'feature_constitution106',
   'feature_constitution64',
   'feature_constitution98',
   'feature_constitution92',
   'feature_constitution99'],
  30: ['feature_constitution83',
   'feature_constitution100',
   'feature_constitution76',
   'feature_constitution89'],
  31: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  32: ['feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution85',
   'feature_constitution1',
   'feature_constitution62',
   'feature_constitution80',
   'feature_constitution84'],
  33: ['feature_constitution60',
   'feature_constitution87',
   'feature_constitution9',
   'feature_constitution33',
   'feature_constitution45',
   'feature_constitution47',
   'feature_constitution54',
   'feature_constitution95'],
  34: ['feature_constitution35',
   'feature_constitution105',
   'feature_constitution109',
   'feature_constitution113',
   'feature_constitution4',
   'feature_constitution49']},
 'dexterity': {0: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  1: ['feature_dexterity3',
   'feature_dexterity4',
   'feature_dexterity5',
   'feature_dexterity6',
   'feature_dexterity7',
   'feature_dexterity8',
   'feature_dexterity11',
   'feature_dexterity12',
   'feature_dexterity13',
   'feature_dexterity14']},
 'intelligence': {0: ['feature_intelligence5', 'feature_intelligence12'],
  1: ['feature_intelligence6', 'feature_intelligence7'],
  2: ['feature_intelligence1', 'feature_intelligence8'],
  3: ['feature_intelligence2', 'feature_intelligence3'],
  4: ['feature_intelligence9', 'feature_intelligence10'],
  5: ['feature_intelligence4', 'feature_intelligence11']},
 'strength': {0: ['feature_strength14', 'feature_strength34'],
  1: ['feature_strength8', 'feature_strength28'],
  2: ['feature_strength7', 'feature_strength35'],
  3: ['feature_strength26', 'feature_strength33'],
  4: ['feature_strength20', 'feature_strength38'],
  5: ['feature_strength12', 'feature_strength30'],
  6: ['feature_strength15', 'feature_strength27'],
  7: ['feature_strength18', 'feature_strength37'],
  8: ['feature_strength9', 'feature_strength22'],
  9: ['feature_strength6', 'feature_strength17'],
  10: ['feature_strength1', 'feature_strength4'],
  11: ['feature_strength10', 'feature_strength36'],
  12: ['feature_strength3', 'feature_strength19'],
  13: ['feature_strength11', 'feature_strength21'],
  14: ['feature_strength16', 'feature_strength23'],
  15: ['feature_strength5', 'feature_strength13'],
  16: ['feature_strength24', 'feature_strength29'],
  17: ['feature_strength25', 'feature_strength31'],
  18: ['feature_strength2', 'feature_strength32']},
 'wisdom': {0: ['feature_wisdom6', 'feature_wisdom11'],
  1: ['feature_wisdom9', 'feature_wisdom22'],
  2: ['feature_wisdom23', 'feature_wisdom32'],
  3: ['feature_wisdom18', 'feature_wisdom25'],
  4: ['feature_wisdom10', 'feature_wisdom19'],
  5: ['feature_wisdom8', 'feature_wisdom26'],
  6: ['feature_wisdom36', 'feature_wisdom42'],
  7: ['feature_wisdom31',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39'],
  8: ['feature_wisdom17', 'feature_wisdom29'],
  9: ['feature_wisdom21', 'feature_wisdom28'],
  10: ['feature_wisdom15', 'feature_wisdom27'],
  11: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45',
   'feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  12: ['feature_wisdom5',
   'feature_wisdom41',
   'feature_wisdom40',
   'feature_wisdom44'],
  13: ['feature_wisdom1',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom35',
   'feature_wisdom13',
   'feature_wisdom34'],
  14: ['feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43']}

   },


'information_variation_hard': {
'charisma': {
  0: ['feature_charisma68', 'feature_charisma82'],
  1: ['feature_charisma8', 'feature_charisma15'],
  2: ['feature_charisma22', 'feature_charisma60'],
  3: ['feature_charisma46', 'feature_charisma66'],
  4: ['feature_charisma10', 'feature_charisma78'],
  5: ['feature_charisma28', 'feature_charisma53'],
  6: ['feature_charisma57', 'feature_charisma83'],
  7: ['feature_charisma12', 'feature_charisma80'],
  8: ['feature_charisma27', 'feature_charisma77'],
  9: ['feature_charisma2', 'feature_charisma24'],
  10: ['feature_charisma31', 'feature_charisma51'],
  11: ['feature_charisma23', 'feature_charisma39'],
  12: ['feature_charisma11', 'feature_charisma58'],
  13: ['feature_charisma32', 'feature_charisma48'],
  14: ['feature_charisma13', 'feature_charisma50'],
  15: ['feature_charisma44', 'feature_charisma74'],
  16: ['feature_charisma16', 'feature_charisma35'],
  17: ['feature_charisma30', 'feature_charisma38'],
  18: ['feature_charisma21', 'feature_charisma36'],
  19: ['feature_charisma34', 'feature_charisma55'],
  20: ['feature_charisma29', 'feature_charisma71'],
  21: ['feature_charisma20', 'feature_charisma64'],
  22: ['feature_charisma26', 'feature_charisma67'],
  23: ['feature_charisma43',
   'feature_charisma63',
   'feature_charisma70',
   'feature_charisma85'],
  24: ['feature_charisma56', 'feature_charisma65'],
  25: ['feature_charisma3', 'feature_charisma45'],
  26: ['feature_charisma42', 'feature_charisma75'],
  27: ['feature_charisma49', 'feature_charisma73'],
  28: ['feature_charisma6', 'feature_charisma54'],
  29: ['feature_charisma7', 'feature_charisma72'],
  30: ['feature_charisma25', 'feature_charisma47'],
  31: ['feature_charisma40', 'feature_charisma61'],
  32: ['feature_charisma52', 'feature_charisma62'],
  33: ['feature_charisma41', 'feature_charisma59'],
  34: ['feature_charisma5', 'feature_charisma79'],
  35: ['feature_charisma84', 'feature_charisma86'],
  36: ['feature_charisma4', 'feature_charisma17'],
  37: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  38: ['feature_charisma9',
   'feature_charisma69',
   'feature_charisma1',
   'feature_charisma19'],
  39: ['feature_charisma14', 'feature_charisma33']},
 'constitution': {0: ['feature_constitution8', 'feature_constitution17'],
  1: ['feature_constitution59', 'feature_constitution81'],
  2: ['feature_constitution53', 'feature_constitution71'],
  3: ['feature_constitution30', 'feature_constitution42'],
  4: ['feature_constitution86', 'feature_constitution94'],
  5: ['feature_constitution83', 'feature_constitution100'],
  6: ['feature_constitution18', 'feature_constitution39'],
  7: ['feature_constitution11', 'feature_constitution28'],
  8: ['feature_constitution76', 'feature_constitution89'],
  9: ['feature_constitution52', 'feature_constitution69'],
  10: ['feature_constitution58', 'feature_constitution68'],
  11: ['feature_constitution24', 'feature_constitution82'],
  12: ['feature_constitution4', 'feature_constitution49'],
  13: ['feature_constitution16', 'feature_constitution40'],
  14: ['feature_constitution41', 'feature_constitution108'],
  15: ['feature_constitution34', 'feature_constitution36'],
  16: ['feature_constitution3', 'feature_constitution23'],
  17: ['feature_constitution75', 'feature_constitution106'],
  18: ['feature_constitution31', 'feature_constitution104'],
  19: ['feature_constitution21', 'feature_constitution70'],
  20: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  21: ['feature_constitution63', 'feature_constitution65'],
  22: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  23: ['feature_constitution15', 'feature_constitution37'],
  24: ['feature_constitution97', 'feature_constitution107'],
  25: ['feature_constitution64',
   'feature_constitution98',
   'feature_constitution92',
   'feature_constitution99'],
  26: ['feature_constitution67',
   'feature_constitution111',
   'feature_constitution38',
   'feature_constitution114'],
  27: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  28: ['feature_constitution72',
   'feature_constitution88',
   'feature_constitution90',
   'feature_constitution103'],
  29: ['feature_constitution80',
   'feature_constitution84',
   'feature_constitution1',
   'feature_constitution62'],
  30: ['feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution85'],
  31: ['feature_constitution2', 'feature_constitution73'],
  32: ['feature_constitution22', 'feature_constitution25'],
  33: ['feature_constitution19', 'feature_constitution78'],
  34: ['feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution77'],
  35: ['feature_constitution9',
   'feature_constitution33',
   'feature_constitution46',
   'feature_constitution60',
   'feature_constitution87',
   'feature_constitution112',
   'feature_constitution54',
   'feature_constitution95',
   'feature_constitution45',
   'feature_constitution47',
   'feature_constitution14',
   'feature_constitution51',
   'feature_constitution61',
   'feature_constitution96'],
  36: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution74',
   'feature_constitution109',
   'feature_constitution113',
   'feature_constitution35',
   'feature_constitution105'],
  37: ['feature_constitution29',
   'feature_constitution50',
   'feature_constitution12',
   'feature_constitution101']},
 'dexterity': {0: ['feature_dexterity3',
   'feature_dexterity4',
   'feature_dexterity6',
   'feature_dexterity7',
   'feature_dexterity8',
   'feature_dexterity11'],
  1: ['feature_dexterity5',
   'feature_dexterity12',
   'feature_dexterity13',
   'feature_dexterity14'],
  2: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10']},
 'intelligence': {0: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11'],
  1: ['feature_intelligence5',
   'feature_intelligence9',
   'feature_intelligence10',
   'feature_intelligence12'],
  2: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence6',
   'feature_intelligence7']},
 'strength': {0: ['feature_strength3', 'feature_strength19'],
  1: ['feature_strength7', 'feature_strength35'],
  2: ['feature_strength14', 'feature_strength34'],
  3: ['feature_strength2', 'feature_strength32'],
  4: ['feature_strength26', 'feature_strength33'],
  5: ['feature_strength8', 'feature_strength28'],
  6: ['feature_strength16', 'feature_strength23'],
  7: ['feature_strength18', 'feature_strength37'],
  8: ['feature_strength9', 'feature_strength22'],
  9: ['feature_strength20', 'feature_strength38'],
  10: ['feature_strength1',
   'feature_strength4',
   'feature_strength11',
   'feature_strength21'],
  11: ['feature_strength10', 'feature_strength36'],
  12: ['feature_strength25', 'feature_strength31'],
  13: ['feature_strength6', 'feature_strength17'],
  14: ['feature_strength15', 'feature_strength27'],
  15: ['feature_strength5', 'feature_strength13'],
  16: ['feature_strength24', 'feature_strength29'],
  17: ['feature_strength12', 'feature_strength30']},
 'wisdom': {0: ['feature_wisdom23', 'feature_wisdom32'],
  1: ['feature_wisdom8', 'feature_wisdom26'],
  2: ['feature_wisdom6', 'feature_wisdom11'],
  3: ['feature_wisdom36', 'feature_wisdom42'],
  4: ['feature_wisdom9', 'feature_wisdom22'],
  5: ['feature_wisdom18', 'feature_wisdom25'],
  6: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  7: ['feature_wisdom31',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39'],
  8: ['feature_wisdom10', 'feature_wisdom19'],
  9: ['feature_wisdom17', 'feature_wisdom29'],
  10: ['feature_wisdom13'],
  11: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45'],
  12: ['feature_wisdom5',
   'feature_wisdom41',
   'feature_wisdom40',
   'feature_wisdom44'],
  13: ['feature_wisdom15', 'feature_wisdom27'],
  14: ['feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom3',
   'feature_wisdom43'],
  15: ['feature_wisdom1',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35'],
  16: ['feature_wisdom21', 'feature_wisdom28']}
  }


}









dict_clusters = {
    'onc': {

'charisma': {
  0: ['feature_charisma25', 'feature_charisma47'],
  1: ['feature_charisma49', 'feature_charisma73'],
  2: ['feature_charisma30', 'feature_charisma38'],
  3: ['feature_charisma8', 'feature_charisma15'],
  4: ['feature_charisma10', 'feature_charisma78'],
  5: ['feature_charisma44', 'feature_charisma74'],
  6: ['feature_charisma20', 'feature_charisma64'],
  7: ['feature_charisma5', 'feature_charisma79'],
  8: ['feature_charisma42', 'feature_charisma75'],
  9: ['feature_charisma68', 'feature_charisma82'],
  10: ['feature_charisma57', 'feature_charisma83'],
  11: ['feature_charisma32', 'feature_charisma48'],
  12: ['feature_charisma41', 'feature_charisma59'],
  13: ['feature_charisma34', 'feature_charisma55'],
  14: ['feature_charisma22', 'feature_charisma60'],
  15: ['feature_charisma56', 'feature_charisma65'],
  16: ['feature_charisma2', 'feature_charisma24'],
  17: ['feature_charisma3', 'feature_charisma45'],
  18: ['feature_charisma9', 'feature_charisma69'],
  19: ['feature_charisma1', 'feature_charisma19'],
  20: ['feature_charisma84', 'feature_charisma86'],
  21: ['feature_charisma27', 'feature_charisma77'],
  22: ['feature_charisma23', 'feature_charisma39'],
  23: ['feature_charisma16', 'feature_charisma35'],
  24: ['feature_charisma31', 'feature_charisma51'],
  25: ['feature_charisma6', 'feature_charisma54'],
  26: ['feature_charisma40', 'feature_charisma61'],
  27: ['feature_charisma4', 'feature_charisma17'],
  28: ['feature_charisma26', 'feature_charisma67'],
  29: ['feature_charisma12', 'feature_charisma80'],
  30: ['feature_charisma7', 'feature_charisma72'],
  31: ['feature_charisma13', 'feature_charisma50'],
  32: ['feature_charisma46', 'feature_charisma66'],
  33: ['feature_charisma52', 'feature_charisma62'],
  34: ['feature_charisma28', 'feature_charisma53'],
  35: ['feature_charisma29', 'feature_charisma71'],
  36: ['feature_charisma14', 'feature_charisma33'],
  37: ['feature_charisma21', 'feature_charisma36'],
  38: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  39: ['feature_charisma43',
   'feature_charisma63',
   'feature_charisma70',
   'feature_charisma85'],
  40: ['feature_charisma11', 'feature_charisma58']},

 'constitution': {
  0: ['feature_constitution52', 'feature_constitution69'],
  1: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution74'],
  2: ['feature_constitution83', 'feature_constitution100'],
  3: ['feature_constitution86', 'feature_constitution94'],
  4: ['feature_constitution8', 'feature_constitution17'],
  5: ['feature_constitution41', 'feature_constitution108'],
  6: ['feature_constitution21', 'feature_constitution70'],
  7: ['feature_constitution31', 'feature_constitution104'],
  8: ['feature_constitution58', 'feature_constitution68'],
  9: ['feature_constitution18',
   'feature_constitution39',
   'feature_constitution97',
   'feature_constitution107'],
  10: ['feature_constitution76', 'feature_constitution89'],
  11: ['feature_constitution16', 'feature_constitution40'],
  12: ['feature_constitution53', 'feature_constitution71'],
  13: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  14: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  15: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  16: ['feature_constitution64',
   'feature_constitution92',
   'feature_constitution98',
   'feature_constitution99'],
  17: ['feature_constitution22', 'feature_constitution25'],
  18: ['feature_constitution15', 'feature_constitution37'],
  19: ['feature_constitution46', 'feature_constitution112'],
  20: ['feature_constitution3', 'feature_constitution23'],
  21: ['feature_constitution59', 'feature_constitution81'],
  22: ['feature_constitution24', 'feature_constitution82'],
  23: ['feature_constitution75', 'feature_constitution106'],
  24: ['feature_constitution12',
   'feature_constitution29',
   'feature_constitution50',
   'feature_constitution101'],
  25: ['feature_constitution38',
   'feature_constitution67',
   'feature_constitution111',
   'feature_constitution114'],
  26: ['feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution77'],
  27: ['feature_constitution11', 'feature_constitution28'],
  28: ['feature_constitution1',
   'feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution62',
   'feature_constitution80',
   'feature_constitution84',
   'feature_constitution85'],
  29: ['feature_constitution30', 'feature_constitution42'],
  30: ['feature_constitution61', 'feature_constitution96'],
  31: ['feature_constitution14', 'feature_constitution51'],
  32: ['feature_constitution19', 'feature_constitution78'],
  33: ['feature_constitution2',
   'feature_constitution63',
   'feature_constitution65',
   'feature_constitution73'],
  34: ['feature_constitution72',
   'feature_constitution88',
   'feature_constitution90',
   'feature_constitution103'],
  35: ['feature_constitution45',
   'feature_constitution47',
   'feature_constitution54',
   'feature_constitution95'],
  36: ['feature_constitution109',
   'feature_constitution113',
   'feature_constitution34',
   'feature_constitution36',
   'feature_constitution4',
   'feature_constitution35',
   'feature_constitution49',
   'feature_constitution105'],
  37: ['feature_constitution9',
   'feature_constitution33',
   'feature_constitution60',
   'feature_constitution87']},

 'dexterity': {
  0: ['feature_dexterity4', 'feature_dexterity7'],
  1: ['feature_dexterity5', 'feature_dexterity13'],
  2: ['feature_dexterity3', 'feature_dexterity8'],
  3: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  4: ['feature_dexterity6', 'feature_dexterity11'],
  5: ['feature_dexterity12', 'feature_dexterity14']},

 'intelligence': {
  0: ['feature_intelligence6', 'feature_intelligence7'],
  1: ['feature_intelligence5', 'feature_intelligence12'],
  2: ['feature_intelligence9', 'feature_intelligence10'],
  3: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11'],
  4: ['feature_intelligence2', 'feature_intelligence3']},

 'strength': {
  0: ['feature_strength6', 'feature_strength17'],
  1: ['feature_strength14', 'feature_strength34'],
  2: ['feature_strength24', 'feature_strength29'],
  3: ['feature_strength9', 'feature_strength22'],
  4: ['feature_strength18', 'feature_strength37'],
  5: ['feature_strength1', 'feature_strength4'],
  6: ['feature_strength12', 'feature_strength30'],
  7: ['feature_strength5', 'feature_strength13'],
  8: ['feature_strength7', 'feature_strength35'],
  9: ['feature_strength20', 'feature_strength38'],
  10: ['feature_strength8', 'feature_strength28'],
  11: ['feature_strength26', 'feature_strength33'],
  12: ['feature_strength11', 'feature_strength21'],
  13: ['feature_strength3', 'feature_strength19'],
  14: ['feature_strength15', 'feature_strength27'],
  15: ['feature_strength10', 'feature_strength36'],
  16: ['feature_strength2', 'feature_strength32'],
  17: ['feature_strength25', 'feature_strength31'],
  18: ['feature_strength16', 'feature_strength23']},

 'wisdom': {
  0: ['feature_wisdom18', 'feature_wisdom25'],
  1: ['feature_wisdom23', 'feature_wisdom32'],
  2: ['feature_wisdom8', 'feature_wisdom26'],
  3: ['feature_wisdom10', 'feature_wisdom19'],
  4: ['feature_wisdom6', 'feature_wisdom11'],
  5: ['feature_wisdom17', 'feature_wisdom29'],
  6: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44'],
  7: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  8: ['feature_wisdom15', 'feature_wisdom27'],
  9: ['feature_wisdom21', 'feature_wisdom28'],
  10: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45'],
  11: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  12: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35'],
  13: ['feature_wisdom9',
   'feature_wisdom22',
   'feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43']}
    },

'denoise': {
 'charisma': {
  0: ['feature_charisma32', 'feature_charisma48'],
  1: ['feature_charisma25', 'feature_charisma47'],
  2: ['feature_charisma57', 'feature_charisma83'],
  3: ['feature_charisma13', 'feature_charisma50'],
  4: ['feature_charisma27', 'feature_charisma77'],
  5: ['feature_charisma42', 'feature_charisma75'],
  6: ['feature_charisma34', 'feature_charisma55'],
  7: ['feature_charisma9', 'feature_charisma69'],
  8: ['feature_charisma20', 'feature_charisma64'],
  9: ['feature_charisma10', 'feature_charisma78'],
  10: ['feature_charisma44', 'feature_charisma74'],
  11: ['feature_charisma40', 'feature_charisma61'],
  12: ['feature_charisma84', 'feature_charisma86'],
  13: ['feature_charisma7', 'feature_charisma72'],
  14: ['feature_charisma43',
   'feature_charisma63',
   'feature_charisma70',
   'feature_charisma85'],
  15: ['feature_charisma52', 'feature_charisma62'],
  16: ['feature_charisma49', 'feature_charisma73'],
  17: ['feature_charisma8', 'feature_charisma15'],
  18: ['feature_charisma1', 'feature_charisma19'],
  19: ['feature_charisma3', 'feature_charisma45'],
  20: ['feature_charisma2', 'feature_charisma24'],
  21: ['feature_charisma46', 'feature_charisma66'],
  22: ['feature_charisma16', 'feature_charisma35'],
  23: ['feature_charisma6', 'feature_charisma54'],
  24: ['feature_charisma5',
   'feature_charisma41',
   'feature_charisma59',
   'feature_charisma79'],
  25: ['feature_charisma26', 'feature_charisma67'],
  26: ['feature_charisma29', 'feature_charisma71'],
  27: ['feature_charisma68',
   'feature_charisma82',
   'feature_charisma23',
   'feature_charisma39'],
  28: ['feature_charisma22',
   'feature_charisma56',
   'feature_charisma60',
   'feature_charisma65'],
  29: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  30: ['feature_charisma12', 'feature_charisma80'],
  31: ['feature_charisma11', 'feature_charisma58'],
  32: ['feature_charisma4',
   'feature_charisma17',
   'feature_charisma30',
   'feature_charisma38'],
  33: ['feature_charisma14',
   'feature_charisma33',
   'feature_charisma31',
   'feature_charisma51'],
  34: ['feature_charisma21',
   'feature_charisma28',
   'feature_charisma36',
   'feature_charisma53']},

 'constitution': {
  0: ['feature_constitution8', 'feature_constitution17'],
  1: ['feature_constitution86', 'feature_constitution94'],
  2: ['feature_constitution52', 'feature_constitution69'],
  3: ['feature_constitution75', 'feature_constitution106'],
  4: ['feature_constitution109', 'feature_constitution113'],
  5: ['feature_constitution16', 'feature_constitution40'],
  6: ['feature_constitution41', 'feature_constitution108'],
  7: ['feature_constitution19', 'feature_constitution78'],
  8: ['feature_constitution59', 'feature_constitution81'],
  9: ['feature_constitution58', 'feature_constitution68'],
  10: ['feature_constitution46', 'feature_constitution112'],
  11: ['feature_constitution76', 'feature_constitution89'],
  12: ['feature_constitution11', 'feature_constitution28'],
  13: ['feature_constitution53', 'feature_constitution71'],
  14: ['feature_constitution22', 'feature_constitution25'],
  15: ['feature_constitution21', 'feature_constitution70'],
  16: ['feature_constitution32',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution77'],
  17: ['feature_constitution18',
   'feature_constitution39',
   'feature_constitution97',
   'feature_constitution107'],
  18: ['feature_constitution3', 'feature_constitution23'],
  19: ['feature_constitution31', 'feature_constitution104'],
  20: ['feature_constitution83', 'feature_constitution100'],
  21: ['feature_constitution61', 'feature_constitution96'],
  22: ['feature_constitution1',
   'feature_constitution20',
   'feature_constitution26',
   'feature_constitution43',
   'feature_constitution62',
   'feature_constitution80',
   'feature_constitution84',
   'feature_constitution85'],
  23: ['feature_constitution2',
   'feature_constitution63',
   'feature_constitution65',
   'feature_constitution73'],
  24: ['feature_constitution7',
   'feature_constitution13',
   'feature_constitution27',
   'feature_constitution79'],
  25: ['feature_constitution24', 'feature_constitution82'],
  26: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution10',
   'feature_constitution74'],
  27: ['feature_constitution15', 'feature_constitution37'],
  28: ['feature_constitution72',
   'feature_constitution88',
   'feature_constitution90',
   'feature_constitution103'],
  29: ['feature_constitution44',
   'feature_constitution55',
   'feature_constitution66',
   'feature_constitution93'],
  30: ['feature_constitution38',
   'feature_constitution67',
   'feature_constitution111',
   'feature_constitution114'],
  31: ['feature_constitution56',
   'feature_constitution91',
   'feature_constitution102',
   'feature_constitution110'],
  32: ['feature_constitution30',
   'feature_constitution42',
   'feature_constitution14',
   'feature_constitution51'],
  33: ['feature_constitution12',
   'feature_constitution29',
   'feature_constitution50',
   'feature_constitution101'],
  34: ['feature_constitution54',
   'feature_constitution95',
   'feature_constitution45',
   'feature_constitution47'],
  35: ['feature_constitution64',
   'feature_constitution92',
   'feature_constitution98',
   'feature_constitution99'],
  36: ['feature_constitution4',
   'feature_constitution34',
   'feature_constitution35',
   'feature_constitution36',
   'feature_constitution49',
   'feature_constitution105'],
  37: ['feature_constitution9',
   'feature_constitution33',
   'feature_constitution60',
   'feature_constitution87']},

 'dexterity': {
 0: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  1: ['feature_dexterity4', 'feature_dexterity7'],
  2: ['feature_dexterity12', 'feature_dexterity14'],
  3: ['feature_dexterity6', 'feature_dexterity11'],
  4: ['feature_dexterity3', 'feature_dexterity8'],
  5: ['feature_dexterity5', 'feature_dexterity13']},

 'intelligence': {
 0: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence9',
   'feature_intelligence10'],
  1: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11'],
  2: ['feature_intelligence5', 'feature_intelligence12'],
  3: ['feature_intelligence6', 'feature_intelligence7']},

 'strength': {
  0: ['feature_strength14', 'feature_strength34'],
  1: ['feature_strength6', 'feature_strength17'],
  2: ['feature_strength5', 'feature_strength13'],
  3: ['feature_strength9', 'feature_strength22'],
  4: ['feature_strength20', 'feature_strength38'],
  5: ['feature_strength12', 'feature_strength30'],
  6: ['feature_strength18', 'feature_strength37'],
  7: ['feature_strength10', 'feature_strength36'],
  8: ['feature_strength24', 'feature_strength29'],
  9: ['feature_strength25', 'feature_strength31'],
  10: ['feature_strength7', 'feature_strength35'],
  11: ['feature_strength8', 'feature_strength28'],
  12: ['feature_strength2',
   'feature_strength16',
   'feature_strength23',
   'feature_strength32'],
  13: ['feature_strength26',
   'feature_strength33',
   'feature_strength1',
   'feature_strength4',
   'feature_strength11',
   'feature_strength21',
   'feature_strength15',
   'feature_strength27'],
  14: ['feature_strength3', 'feature_strength19']},

 'wisdom': {
  0: ['feature_wisdom21', 'feature_wisdom28'],
  1: ['feature_wisdom23', 'feature_wisdom32'],
  2: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  3: ['feature_wisdom6', 'feature_wisdom11'],
  4: ['feature_wisdom15', 'feature_wisdom27'],
  5: ['feature_wisdom8', 'feature_wisdom26'],
  6: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  7: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45'],
  8: ['feature_wisdom18', 'feature_wisdom25'],
  9: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35',
   'feature_wisdom10',
   'feature_wisdom17',
   'feature_wisdom19',
   'feature_wisdom29'],
  10: ['feature_wisdom3',
   'feature_wisdom9',
   'feature_wisdom22',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43'],
  11: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44']}
   },

'information_variation':{
'charisma': {
  0: ['feature_charisma30', 'feature_charisma38'],
  1: ['feature_charisma44', 'feature_charisma74'],
  2: ['feature_charisma27', 'feature_charisma77'],
  3: ['feature_charisma25', 'feature_charisma47'],
  4: ['feature_charisma32', 'feature_charisma48'],
  5: ['feature_charisma10', 'feature_charisma78'],
  6: ['feature_charisma20', 'feature_charisma64'],
  7: ['feature_charisma8', 'feature_charisma15'],
  8: ['feature_charisma26', 'feature_charisma67'],
  9: ['feature_charisma68', 'feature_charisma82'],
  10: ['feature_charisma7', 'feature_charisma72'],
  11: ['feature_charisma42', 'feature_charisma75'],
  12: ['feature_charisma9', 'feature_charisma69'],
  13: ['feature_charisma56', 'feature_charisma65'],
  14: ['feature_charisma5', 'feature_charisma79'],
  15: ['feature_charisma3', 'feature_charisma45'],
  16: ['feature_charisma41', 'feature_charisma59'],
  17: ['feature_charisma49', 'feature_charisma73'],
  18: ['feature_charisma84', 'feature_charisma86'],
  19: ['feature_charisma57', 'feature_charisma83'],
  20: ['feature_charisma23', 'feature_charisma39'],
  21: ['feature_charisma22', 'feature_charisma60'],
  22: ['feature_charisma12', 'feature_charisma80'],
  23: ['feature_charisma1', 'feature_charisma19'],
  24: ['feature_charisma6', 'feature_charisma54'],
  25: ['feature_charisma34', 'feature_charisma55'],
  26: ['feature_charisma14', 'feature_charisma33'],
  27: ['feature_charisma52', 'feature_charisma62'],
  28: ['feature_charisma2', 'feature_charisma24'],
  29: ['feature_charisma46', 'feature_charisma66'],
  30: ['feature_charisma40', 'feature_charisma61'],
  31: ['feature_charisma4', 'feature_charisma17'],
  32: ['feature_charisma16', 'feature_charisma35'],
  33: ['feature_charisma63', 'feature_charisma85'],
  34: ['feature_charisma43', 'feature_charisma70'],
  35: ['feature_charisma29', 'feature_charisma71'],
  36: ['feature_charisma31', 'feature_charisma51'],
  37: ['feature_charisma21', 'feature_charisma36'],
  38: ['feature_charisma13', 'feature_charisma50'],
  39: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  40: ['feature_charisma28', 'feature_charisma53'],
  41: ['feature_charisma11', 'feature_charisma58']},

 'constitution': {0: ['feature_constitution1',
   'feature_constitution2',
   'feature_constitution3',
   'feature_constitution4',
   'feature_constitution8',
   'feature_constitution9',
   'feature_constitution11',
   'feature_constitution12',
   'feature_constitution14',
   'feature_constitution15',
   'feature_constitution16',
   'feature_constitution17',
   'feature_constitution19',
   'feature_constitution20',
   'feature_constitution21',
   'feature_constitution23',
   'feature_constitution24',
   'feature_constitution26',
   'feature_constitution28',
   'feature_constitution29',
   'feature_constitution30',
   'feature_constitution31',
   'feature_constitution33',
   'feature_constitution34',
   'feature_constitution35',
   'feature_constitution36',
   'feature_constitution37',
   'feature_constitution40',
   'feature_constitution41',
   'feature_constitution42',
   'feature_constitution43',
   'feature_constitution44',
   'feature_constitution45',
   'feature_constitution46',
   'feature_constitution47',
   'feature_constitution49',
   'feature_constitution50',
   'feature_constitution51',
   'feature_constitution52',
   'feature_constitution53',
   'feature_constitution54',
   'feature_constitution55',
   'feature_constitution56',
   'feature_constitution58',
   'feature_constitution59',
   'feature_constitution60',
   'feature_constitution61',
   'feature_constitution62',
   'feature_constitution63',
   'feature_constitution65',
   'feature_constitution66',
   'feature_constitution68',
   'feature_constitution69',
   'feature_constitution70',
   'feature_constitution71',
   'feature_constitution72',
   'feature_constitution73',
   'feature_constitution76',
   'feature_constitution78',
   'feature_constitution80',
   'feature_constitution81',
   'feature_constitution82',
   'feature_constitution83',
   'feature_constitution84',
   'feature_constitution85',
   'feature_constitution86',
   'feature_constitution87',
   'feature_constitution88',
   'feature_constitution89',
   'feature_constitution90',
   'feature_constitution91',
   'feature_constitution93',
   'feature_constitution94',
   'feature_constitution95',
   'feature_constitution96',
   'feature_constitution100',
   'feature_constitution101',
   'feature_constitution102',
   'feature_constitution103',
   'feature_constitution104',
   'feature_constitution105',
   'feature_constitution108',
   'feature_constitution109',
   'feature_constitution110',
   'feature_constitution112',
   'feature_constitution113'],
  1: ['feature_constitution5',
   'feature_constitution6',
   'feature_constitution7',
   'feature_constitution10',
   'feature_constitution13',
   'feature_constitution18',
   'feature_constitution22',
   'feature_constitution25',
   'feature_constitution27',
   'feature_constitution32',
   'feature_constitution38',
   'feature_constitution39',
   'feature_constitution48',
   'feature_constitution57',
   'feature_constitution64',
   'feature_constitution67',
   'feature_constitution74',
   'feature_constitution75',
   'feature_constitution77',
   'feature_constitution79',
   'feature_constitution92',
   'feature_constitution97',
   'feature_constitution98',
   'feature_constitution99',
   'feature_constitution106',
   'feature_constitution107',
   'feature_constitution111',
   'feature_constitution114']},

 'dexterity': {
 0: ['feature_dexterity5', 'feature_dexterity13'],
  1: ['feature_dexterity4', 'feature_dexterity7'],
  2: ['feature_dexterity3', 'feature_dexterity8'],
  3: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  4: ['feature_dexterity6', 'feature_dexterity11'],
  5: ['feature_dexterity12', 'feature_dexterity14']},

 'intelligence': {
 0: ['feature_intelligence5',
   'feature_intelligence6',
   'feature_intelligence7',
   'feature_intelligence12'],
  1: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence9',
   'feature_intelligence10'],
  2: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11']},


 'strength': {0: ['feature_strength14', 'feature_strength34'],
  1: ['feature_strength20', 'feature_strength38'],
  2: ['feature_strength6', 'feature_strength17'],
  3: ['feature_strength24', 'feature_strength29'],
  4: ['feature_strength2', 'feature_strength32'],
  5: ['feature_strength18', 'feature_strength37'],
  6: ['feature_strength7', 'feature_strength35'],
  7: ['feature_strength9', 'feature_strength22'],
  8: ['feature_strength12', 'feature_strength30'],
  9: ['feature_strength8', 'feature_strength28'],
  10: ['feature_strength16', 'feature_strength23'],
  11: ['feature_strength11',
   'feature_strength21',
   'feature_strength26',
   'feature_strength33',
   'feature_strength15',
   'feature_strength27',
   'feature_strength1',
   'feature_strength4'],
  12: ['feature_strength25',
   'feature_strength31',
   'feature_strength5',
   'feature_strength13'],
  13: ['feature_strength3',
   'feature_strength19',
   'feature_strength10',
   'feature_strength36']},

 'wisdom': {0: ['feature_wisdom2',
   'feature_wisdom4',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45',
   'feature_wisdom46'],
  1: ['feature_wisdom10',
   'feature_wisdom17',
   'feature_wisdom19',
   'feature_wisdom29'],
  2: ['feature_wisdom23', 'feature_wisdom32'],
  3: ['feature_wisdom6', 'feature_wisdom11'],
  4: ['feature_wisdom18', 'feature_wisdom25'],
  5: ['feature_wisdom8', 'feature_wisdom26'],
  6: ['feature_wisdom40', 'feature_wisdom44'],
  7: ['feature_wisdom5', 'feature_wisdom41'],
  8: ['feature_wisdom21', 'feature_wisdom28'],
  9: ['feature_wisdom15', 'feature_wisdom27'],
  10: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  11: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35'],
  12: ['feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43',
   'feature_wisdom9',
   'feature_wisdom22']}
   },

   'mutual_information':
   {'charisma': {0: ['feature_charisma30', 'feature_charisma38'],
  1: ['feature_charisma20', 'feature_charisma64'],
  2: ['feature_charisma8', 'feature_charisma15'],
  3: ['feature_charisma32', 'feature_charisma48'],
  4: ['feature_charisma26', 'feature_charisma67'],
  5: ['feature_charisma10', 'feature_charisma78'],
  6: ['feature_charisma25', 'feature_charisma47'],
  7: ['feature_charisma27', 'feature_charisma77'],
  8: ['feature_charisma68', 'feature_charisma82'],
  9: ['feature_charisma44', 'feature_charisma74'],
  10: ['feature_charisma56', 'feature_charisma65'],
  11: ['feature_charisma42', 'feature_charisma75'],
  12: ['feature_charisma3', 'feature_charisma45'],
  13: ['feature_charisma57', 'feature_charisma83'],
  14: ['feature_charisma7', 'feature_charisma72'],
  15: ['feature_charisma23', 'feature_charisma39'],
  16: ['feature_charisma5', 'feature_charisma79'],
  17: ['feature_charisma9', 'feature_charisma69'],
  18: ['feature_charisma49', 'feature_charisma73'],
  19: ['feature_charisma22', 'feature_charisma60'],
  20: ['feature_charisma41', 'feature_charisma59'],
  21: ['feature_charisma1', 'feature_charisma19'],
  22: ['feature_charisma12', 'feature_charisma80'],
  23: ['feature_charisma84', 'feature_charisma86'],
  24: ['feature_charisma6', 'feature_charisma54'],
  25: ['feature_charisma63', 'feature_charisma85'],
  26: ['feature_charisma14', 'feature_charisma33'],
  27: ['feature_charisma2', 'feature_charisma24'],
  28: ['feature_charisma16', 'feature_charisma35'],
  29: ['feature_charisma4', 'feature_charisma17'],
  30: ['feature_charisma52', 'feature_charisma62'],
  31: ['feature_charisma34', 'feature_charisma55'],
  32: ['feature_charisma40', 'feature_charisma61'],
  33: ['feature_charisma43', 'feature_charisma70'],
  34: ['feature_charisma31', 'feature_charisma51'],
  35: ['feature_charisma29', 'feature_charisma71'],
  36: ['feature_charisma46', 'feature_charisma66'],
  37: ['feature_charisma21', 'feature_charisma36'],
  38: ['feature_charisma13', 'feature_charisma50'],
  39: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  40: ['feature_charisma11', 'feature_charisma58'],
  41: ['feature_charisma28', 'feature_charisma53']},

 'constitution': {
 0: ['feature_constitution83', 'feature_constitution100'],
 1: ['feature_constitution1', 'feature_constitution62'],
 2: ['feature_constitution53', 'feature_constitution71'],
 3: ['feature_constitution30', 'feature_constitution42'],
 4: ['feature_constitution32',
  'feature_constitution48',
  'feature_constitution57',
  'feature_constitution77'],
 5: ['feature_constitution9',
  'feature_constitution33',
  'feature_constitution46',
  'feature_constitution60',
  'feature_constitution87',
  'feature_constitution112'],
 6: ['feature_constitution15', 'feature_constitution37'],
 7: ['feature_constitution19', 'feature_constitution78'],
 8: ['feature_constitution7',
  'feature_constitution13',
  'feature_constitution27',
  'feature_constitution79'],
 9: ['feature_constitution12',
  'feature_constitution29',
  'feature_constitution50',
  'feature_constitution101'],
 10: ['feature_constitution44',
  'feature_constitution55',
  'feature_constitution66',
  'feature_constitution93'],
 11: ['feature_constitution4', 'feature_constitution49'],
 12: ['feature_constitution18',
  'feature_constitution39',
  'feature_constitution97',
  'feature_constitution107'],
 13: ['feature_constitution2',
  'feature_constitution63',
  'feature_constitution65',
  'feature_constitution73'],
 14: ['feature_constitution56',
  'feature_constitution91',
  'feature_constitution102',
  'feature_constitution110'],
 15: ['feature_constitution38',
  'feature_constitution67',
  'feature_constitution111',
  'feature_constitution114'],
 16: ['feature_constitution64',
  'feature_constitution92',
  'feature_constitution98',
  'feature_constitution99'],
 17: ['feature_constitution5',
  'feature_constitution6',
  'feature_constitution10',
  'feature_constitution74'],
 18: ['feature_constitution75', 'feature_constitution106'],
 19: ['feature_constitution45',
  'feature_constitution47',
  'feature_constitution54',
  'feature_constitution95'],
 20: ['feature_constitution86', 'feature_constitution94'],
 21: ['feature_constitution72',
  'feature_constitution88',
  'feature_constitution90',
  'feature_constitution103'],
 22: ['feature_constitution61', 'feature_constitution96'],
 23: ['feature_constitution21', 'feature_constitution70'],
 24: ['feature_constitution58', 'feature_constitution68'],
 25: ['feature_constitution3', 'feature_constitution23'],
 26: ['feature_constitution76', 'feature_constitution89'],
 27: ['feature_constitution20', 'feature_constitution43'],
 28: ['feature_constitution35', 'feature_constitution105'],
 29: ['feature_constitution24', 'feature_constitution82'],
 30: ['feature_constitution31', 'feature_constitution104'],
 31: ['feature_constitution52', 'feature_constitution69'],
 32: ['feature_constitution41', 'feature_constitution108'],
 33: ['feature_constitution80', 'feature_constitution84'],
 34: ['feature_constitution16', 'feature_constitution40'],
 35: ['feature_constitution26', 'feature_constitution85'],
 36: ['feature_constitution8', 'feature_constitution17'],
 37: ['feature_constitution59', 'feature_constitution81'],
 38: ['feature_constitution109', 'feature_constitution113'],
 39: ['feature_constitution22', 'feature_constitution25'],
 40: ['feature_constitution11', 'feature_constitution28'],
 41: ['feature_constitution14', 'feature_constitution51'],
 42: ['feature_constitution34', 'feature_constitution36']},

 'dexterity': {
  0: ['feature_dexterity5', 'feature_dexterity13'],
  1: ['feature_dexterity3', 'feature_dexterity8'],
  2: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  3: ['feature_dexterity4', 'feature_dexterity7'],
  4: ['feature_dexterity6', 'feature_dexterity11'],
  5: ['feature_dexterity12', 'feature_dexterity14']},

 'intelligence': {
 0: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11'],
  1: ['feature_intelligence5',
   'feature_intelligence6',
   'feature_intelligence7',
   'feature_intelligence12'],
  2: ['feature_intelligence2',
   'feature_intelligence3',
   'feature_intelligence9',
   'feature_intelligence10']},

 'strength': {
  0: ['feature_strength6', 'feature_strength17'],
  1: ['feature_strength20', 'feature_strength38'],
  2: ['feature_strength14', 'feature_strength34'],
  3: ['feature_strength24', 'feature_strength29'],
  4: ['feature_strength18', 'feature_strength37'],
  5: ['feature_strength9', 'feature_strength22'],
  6: ['feature_strength2', 'feature_strength32'],
  7: ['feature_strength16', 'feature_strength23'],
  8: ['feature_strength3', 'feature_strength19'],
  9: ['feature_strength7', 'feature_strength35'],
  10: ['feature_strength12', 'feature_strength30'],
  11: ['feature_strength8', 'feature_strength28'],
  12: ['feature_strength5', 'feature_strength13'],
  13: ['feature_strength25', 'feature_strength31'],
  14: ['feature_strength10', 'feature_strength36'],
  15: ['feature_strength1',
   'feature_strength4',
   'feature_strength11',
   'feature_strength21'],
  16: ['feature_strength26', 'feature_strength33'],
  17: ['feature_strength15', 'feature_strength27']},

 'wisdom': {0: ['feature_wisdom6', 'feature_wisdom11'],
  1: ['feature_wisdom23', 'feature_wisdom32'],
  2: ['feature_wisdom17', 'feature_wisdom29'],
  3: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45',
   'feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  4: ['feature_wisdom18', 'feature_wisdom25'],
  5: ['feature_wisdom15', 'feature_wisdom27'],
  6: ['feature_wisdom10', 'feature_wisdom19'],
  7: ['feature_wisdom8', 'feature_wisdom26'],
  8: ['feature_wisdom21', 'feature_wisdom28'],
  9: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44'],
  10: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  11: ['feature_wisdom9',
   'feature_wisdom22',
   'feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43'],
  12: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35']}},



   'misto':
   {'charisma': {0: ['feature_charisma30', 'feature_charisma38'],
  1: ['feature_charisma20', 'feature_charisma64'],
  2: ['feature_charisma8', 'feature_charisma15'],
  3: ['feature_charisma32', 'feature_charisma48'],
  4: ['feature_charisma26', 'feature_charisma67'],
  5: ['feature_charisma10', 'feature_charisma78'],
  6: ['feature_charisma25', 'feature_charisma47'],
  7: ['feature_charisma27', 'feature_charisma77'],
  8: ['feature_charisma68', 'feature_charisma82'],
  9: ['feature_charisma44', 'feature_charisma74'],
  10: ['feature_charisma56', 'feature_charisma65'],
  11: ['feature_charisma42', 'feature_charisma75'],
  12: ['feature_charisma3', 'feature_charisma45'],
  13: ['feature_charisma57', 'feature_charisma83'],
  14: ['feature_charisma7', 'feature_charisma72'],
  15: ['feature_charisma23', 'feature_charisma39'],
  16: ['feature_charisma5', 'feature_charisma79'],
  17: ['feature_charisma9', 'feature_charisma69'],
  18: ['feature_charisma49', 'feature_charisma73'],
  19: ['feature_charisma22', 'feature_charisma60'],
  20: ['feature_charisma41', 'feature_charisma59'],
  21: ['feature_charisma1', 'feature_charisma19'],
  22: ['feature_charisma12', 'feature_charisma80'],
  23: ['feature_charisma84', 'feature_charisma86'],
  24: ['feature_charisma6', 'feature_charisma54'],
  25: ['feature_charisma63', 'feature_charisma85'],
  26: ['feature_charisma14', 'feature_charisma33'],
  27: ['feature_charisma2', 'feature_charisma24'],
  28: ['feature_charisma16', 'feature_charisma35'],
  29: ['feature_charisma4', 'feature_charisma17'],
  30: ['feature_charisma52', 'feature_charisma62'],
  31: ['feature_charisma34', 'feature_charisma55'],
  32: ['feature_charisma40', 'feature_charisma61'],
  33: ['feature_charisma43', 'feature_charisma70'],
  34: ['feature_charisma31', 'feature_charisma51'],
  35: ['feature_charisma29', 'feature_charisma71'],
  36: ['feature_charisma46', 'feature_charisma66'],
  37: ['feature_charisma21', 'feature_charisma36'],
  38: ['feature_charisma13', 'feature_charisma50'],
  39: ['feature_charisma18',
   'feature_charisma37',
   'feature_charisma76',
   'feature_charisma81'],
  40: ['feature_charisma11', 'feature_charisma58'],
  41: ['feature_charisma28', 'feature_charisma53']},

 'constitution': {
 0: ['feature_constitution83', 'feature_constitution100'],
 1: ['feature_constitution1', 'feature_constitution62'],
 2: ['feature_constitution53', 'feature_constitution71'],
 3: ['feature_constitution30', 'feature_constitution42'],
 4: ['feature_constitution32',
  'feature_constitution48',
  'feature_constitution57',
  'feature_constitution77'],
 5: ['feature_constitution9',
  'feature_constitution33',
  'feature_constitution46',
  'feature_constitution60',
  'feature_constitution87',
  'feature_constitution112'],
 6: ['feature_constitution15', 'feature_constitution37'],
 7: ['feature_constitution19', 'feature_constitution78'],
 8: ['feature_constitution7',
  'feature_constitution13',
  'feature_constitution27',
  'feature_constitution79'],
 9: ['feature_constitution12',
  'feature_constitution29',
  'feature_constitution50',
  'feature_constitution101'],
 10: ['feature_constitution44',
  'feature_constitution55',
  'feature_constitution66',
  'feature_constitution93'],
 11: ['feature_constitution4', 'feature_constitution49'],
 12: ['feature_constitution18',
  'feature_constitution39',
  'feature_constitution97',
  'feature_constitution107'],
 13: ['feature_constitution2',
  'feature_constitution63',
  'feature_constitution65',
  'feature_constitution73'],
 14: ['feature_constitution56',
  'feature_constitution91',
  'feature_constitution102',
  'feature_constitution110'],
 15: ['feature_constitution38',
  'feature_constitution67',
  'feature_constitution111',
  'feature_constitution114'],
 16: ['feature_constitution64',
  'feature_constitution92',
  'feature_constitution98',
  'feature_constitution99'],
 17: ['feature_constitution5',
  'feature_constitution6',
  'feature_constitution10',
  'feature_constitution74'],
 18: ['feature_constitution75', 'feature_constitution106'],
 19: ['feature_constitution45',
  'feature_constitution47',
  'feature_constitution54',
  'feature_constitution95'],
 20: ['feature_constitution86', 'feature_constitution94'],
 21: ['feature_constitution72',
  'feature_constitution88',
  'feature_constitution90',
  'feature_constitution103'],
 22: ['feature_constitution61', 'feature_constitution96'],
 23: ['feature_constitution21', 'feature_constitution70'],
 24: ['feature_constitution58', 'feature_constitution68'],
 25: ['feature_constitution3', 'feature_constitution23'],
 26: ['feature_constitution76', 'feature_constitution89'],
 27: ['feature_constitution20', 'feature_constitution43'],
 28: ['feature_constitution35', 'feature_constitution105'],
 29: ['feature_constitution24', 'feature_constitution82'],
 30: ['feature_constitution31', 'feature_constitution104'],
 31: ['feature_constitution52', 'feature_constitution69'],
 32: ['feature_constitution41', 'feature_constitution108'],
 33: ['feature_constitution80', 'feature_constitution84'],
 34: ['feature_constitution16', 'feature_constitution40'],
 35: ['feature_constitution26', 'feature_constitution85'],
 36: ['feature_constitution8', 'feature_constitution17'],
 37: ['feature_constitution59', 'feature_constitution81'],
 38: ['feature_constitution109', 'feature_constitution113'],
 39: ['feature_constitution22', 'feature_constitution25'],
 40: ['feature_constitution11', 'feature_constitution28'],
 41: ['feature_constitution14', 'feature_constitution51'],
 42: ['feature_constitution34', 'feature_constitution36']},

 'dexterity': {
 0: ['feature_dexterity5', 'feature_dexterity13'],
  1: ['feature_dexterity4', 'feature_dexterity7'],
  2: ['feature_dexterity3', 'feature_dexterity8'],
  3: ['feature_dexterity1',
   'feature_dexterity2',
   'feature_dexterity9',
   'feature_dexterity10'],
  4: ['feature_dexterity6', 'feature_dexterity11'],
  5: ['feature_dexterity12', 'feature_dexterity14']},


 'intelligence': {
  0: ['feature_intelligence6', 'feature_intelligence7'],
  1: ['feature_intelligence5', 'feature_intelligence12'],
  2: ['feature_intelligence9', 'feature_intelligence10'],
  3: ['feature_intelligence1',
   'feature_intelligence4',
   'feature_intelligence8',
   'feature_intelligence11'],
  4: ['feature_intelligence2', 'feature_intelligence3']},

 'strength': {
  0: ['feature_strength6', 'feature_strength17'],
  1: ['feature_strength14', 'feature_strength34'],
  2: ['feature_strength24', 'feature_strength29'],
  3: ['feature_strength9', 'feature_strength22'],
  4: ['feature_strength18', 'feature_strength37'],
  5: ['feature_strength1', 'feature_strength4'],
  6: ['feature_strength12', 'feature_strength30'],
  7: ['feature_strength5', 'feature_strength13'],
  8: ['feature_strength7', 'feature_strength35'],
  9: ['feature_strength20', 'feature_strength38'],
  10: ['feature_strength8', 'feature_strength28'],
  11: ['feature_strength26', 'feature_strength33'],
  12: ['feature_strength11', 'feature_strength21'],
  13: ['feature_strength3', 'feature_strength19'],
  14: ['feature_strength15', 'feature_strength27'],
  15: ['feature_strength10', 'feature_strength36'],
  16: ['feature_strength2', 'feature_strength32'],
  17: ['feature_strength25', 'feature_strength31'],
  18: ['feature_strength16', 'feature_strength23']},



 'wisdom': {
  0: ['feature_wisdom18', 'feature_wisdom25'],
  1: ['feature_wisdom23', 'feature_wisdom32'],
  2: ['feature_wisdom8', 'feature_wisdom26'],
  3: ['feature_wisdom10', 'feature_wisdom19'],
  4: ['feature_wisdom6', 'feature_wisdom11'],
  5: ['feature_wisdom17', 'feature_wisdom29'],
  6: ['feature_wisdom5',
   'feature_wisdom40',
   'feature_wisdom41',
   'feature_wisdom44'],
  7: ['feature_wisdom2',
   'feature_wisdom7',
   'feature_wisdom12',
   'feature_wisdom46'],
  8: ['feature_wisdom15', 'feature_wisdom27'],
  9: ['feature_wisdom21', 'feature_wisdom28'],
  10: ['feature_wisdom4',
   'feature_wisdom16',
   'feature_wisdom30',
   'feature_wisdom45'],
  11: ['feature_wisdom31',
   'feature_wisdom36',
   'feature_wisdom37',
   'feature_wisdom38',
   'feature_wisdom39',
   'feature_wisdom42'],
  12: ['feature_wisdom1',
   'feature_wisdom13',
   'feature_wisdom14',
   'feature_wisdom20',
   'feature_wisdom34',
   'feature_wisdom35'],
  13: ['feature_wisdom9',
   'feature_wisdom22',
   'feature_wisdom3',
   'feature_wisdom24',
   'feature_wisdom33',
   'feature_wisdom43']}
    },



}


